version: "3"

services:
  app:
    image: weather-playlist:latest
    container_name: weather-playlist-api
    build:
      context: ../src/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5000:80"
